version: "3.9"

services:
  streamer:
    build:
      context: ../../
      dockerfile: src/docker/tss/Dockerfile
    ports:
      - "50051:50051"
      - "8090:8090"
      - "8080:8080"
      - "8081:8081"

  processor:
    depends_on:
      streamer:
        condition: service_healthy
